import pandas as pd
import json
import ast
import re

# --- CONFIG ---
# Assuming your output file is the one generated by the batch script
INPUT_CSV_PATH = "education_output.csv"
CLEAN_SUMMARY_CSV_PATH = "education_summary_clean.csv"

# --- HELPER FUNCTIONS ---

def clean_json_string(escaped_json: str) -> dict:
    """
    Attempts to unescape and parse the JSON stored in the CSV cells,
    handling common issues like double-quotes and potential model output corruption.
    """
    if pd.isna(escaped_json) or escaped_json.strip() == "":
        return {}
    
    # 1. Try to handle model output in Raw_Model_Output which is double-escaped
    try:
        # Replace the literal double-quotes (which escape the quotes within the CSV cell)
        # and parse it as a Python literal string first.
        # This is a common way the model's output ends up in the CSV.
        cleaned = escaped_json.replace('""', '"')
        
        # Sometimes the model output itself is messy (like in your example starting at index 45)
        # We try to fix missing commas/misplaced brackets common in raw output
        cleaned = re.sub(r'}\s*\{', '},{', cleaned)
        cleaned = re.sub(r'\[\s*{', '[{', cleaned)
        cleaned = re.sub(r'}\s*]', '}]', cleaned)
        
        # Fix missing commas between key/value pairs if the model output was corrupted
        # This is a HEURISTIC and might not catch everything!
        cleaned = re.sub(r'""\s*""', '"", ""', cleaned) 
        
        # Handle the JSON array parsing
        # The Raw_Model_Output is typically an array containing the results
        parsed_array = json.loads(cleaned)
        
        # Return the dictionary for the first item (which matches the row)
        if isinstance(parsed_array, list) and parsed_array:
            return parsed_array[0] 
        elif isinstance(parsed_array, dict):
            return parsed_array # Sometimes a single object is returned instead of an array
            
    except Exception as e:
        # If standard JSON parsing fails, log and return empty
        # print(f"Warning: Failed to parse Raw_Model_Output JSON. Error: {e}")
        return {}
        
    return {}


# --- MAIN PROCESSING ---

def normalize_data(input_path: str, output_path: str):
    print(f"Loading data from {input_path}...")
    try:
        # Load the CSV. You might need to adjust the separator based on your local settings.
        df = pd.read_csv(input_path, sep=",")
    except Exception as e:
        print(f"FATAL ERROR: Could not read CSV file. Please check file path and separator. Error: {e}")
        return

    # 1. Filter out the necessary original and extracted columns
    original_cols = ['Name', 'Organization/Law Firm Name', 'City', 'State', 'Country', 'Zipcode', 'Phone Number', 'Reg Code', 'Agent/Attorney']
    extracted_cols = ['Education_Summary', 'Validation_Flags']
    
    df_clean = df[original_cols + extracted_cols].copy()
    
    # 2. Extract and clean data from the Raw_Model_Output column
    print("Extracting clean education details from JSON objects...")
    
    # Create new columns for structured data
    df_clean['Clean_Education_List'] = ''
    df_clean['Clean_Sources'] = ''
    
    for index, row in df.iterrows():
        # Only parse the JSON if the row didn't already have clean data (i.e., if Raw_Model_Output exists)
        if pd.notna(row['Raw_Model_Output']):
            
            # Use Raw_Model_Output to find the corresponding result object
            result_obj = clean_json_string(str(row['Raw_Model_Output']))
            
            # Map the clean extracted fields
            edu_list = result_obj.get('education', [])
            sources = result_obj.get('sources', [])
            
            # Convert the list of education dicts to a clean JSON string for the new column
            df_clean.loc[index, 'Clean_Education_List'] = json.dumps(edu_list, ensure_ascii=False)
            df_clean.loc[index, 'Clean_Sources'] = json.dumps(sources, ensure_ascii=False)

        else:
             # Fallback: if Raw_Model_Output is missing, use the data already in Education_JSON and Education_Sources
             df_clean.loc[index, 'Clean_Education_List'] = row['Education_JSON']
             df_clean.loc[index, 'Clean_Sources'] = row['Education_Sources']


    # 3. Write the final, clean CSV file
    final_columns = original_cols + ['Education_Summary', 'Clean_Education_List', 'Clean_Sources', 'Validation_Flags']
    
    df_clean.to_csv(output_path, index=False, columns=final_columns, encoding='utf-8')
    print(f"\nSuccessfully created clean summary file at: {output_path}")


if __name__ == "__main__":
    normalize_data(INPUT_CSV_PATH, CLEAN_SUMMARY_CSV_PATH)